version: '3'

volumes:
  postgres_data:
      driver: local
  application_data:
      driver: local

services:
  postgres:
      image: postgres:14.4
      container_name: myhabits_psql
      volumes:
        - postgres_data:/var/lib/postgresql
      env_file:
        - application/db_myhabits/postgres.env
      ports:
        - 5432:5432
      restart:
        unless-stopped
  redis:
      image: redis:latest
      container_name: myhabits_redis
      ports:
        - 6379:6379
      restart:
        unless-stopped
  myhabits:
      build: .
      container_name: myhabits_python
      volumes:
        - application_data:/home/python/TeachMeSkills/myhabits
      env_file:
        - app.env
      ports:
        - 5000:5000
      # depends_on:
      #   - postgres
        # - redis
      restart:
        unless-stopped
  worker:
      build: ./
      entrypoint: celery
      container_name: myhabits_worker
      # command: -A task_celery worker -l info -E
      command: -A task_celery worker --loglevel=INFO
      # user: nobody
      # volumes:
      #   - ./examples:/data
      env_file:
          - app.env
      environment:
        CELERY_BROKER_URL: redis://redis
        CELERY_RESULT_BACKEND: redis://redis
        # PYTHONPATH: /data
      # depends_on:
      #   - redis
      #   - myhabits
  flower:
      build: ./
      command: celery -A task_celery flower
      container_name: myhabits_flower
      # volumes:
      #   - ./examples:/data
      # working_dir: /data
      env_file:
        - app.env
      ports:
        - 5555:5555
      environment:
        CELERY_BROKER_URL: redis://redis
        CELERY_RESULT_BACKEND: redis://redis
      # depends_on:
      #   - worker
      #   - redis
      #   - myhabits
    